# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  ###############################################
  # Tests

  desc "Run tests"
  lane :tests do

    scan( 
      project: "Imgur.xcodeproj",
      scheme: "Imgur",
      devices: ["iPhone 14 Pro"],
      code_coverage: true,
      skip_slack: true,
      result_bundle: true
    )
  end

  ###############################################
  # Lint
  desc "SwiftLint"
  lane :runSwiftlint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml",
      raise_if_swiftlint_error: true,
      ignore_exit_status: false,
    )
  end

  ###############################################
  # Build Project
  desc "Development Build"
  lane :development do 
    runSwiftlint
    tests
    
    gym(
      project: "Imgur.xcodeproj",
      configuration: "Debug",
      scheme: "Imgur",
      silent: true,
      skip_package_ipa: true,
      skip_codesigning: true,
      export_method: "development",
      output_directory: "fastlane/ipa/debug"
    )
  end
end
